source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FeatureSwitch_Example', :exclusive => true do
  pod 'FeatureSwitch', :path => '../'
end

target 'FeatureSwitch_Tests', :exclusive => true do
  pod 'FeatureSwitch', :path => '../'

  
end
