source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj 'FeatureSwitch’

target 'FeatureSwitch_Example' do
  pod 'FeatureSwitch', :path => '../'
end

target 'FeatureSwitch_Tests' do
  pod 'FeatureSwitch', :path => '../'

  
end
